server:
  port: 8080
spring:
  # 使用druid数据源
  datasource:
    name: dataSource
    url: jdbc:mysql://localhost:3306/sql_demo?useUnicode=true&zeroDateTimeBehavior=convertToNull&useServerPrepStmts=false&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 2
      min-idle: 2
      validation-query: select count(1)
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
    tomcat:
      max-active: 10
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
    hikari:
      connection-init-sql: set names utf8mb4;

# MyBatis配置
# mybatis.config-location=classpath:mybatis-config.xml
mybatis:
  mapper-locations: classpath*:sqlmap/*.xml
  type-aliases-package: com.kixs.sql.domain.*









